<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Demo extends MAIN_Controller implements AdminModuleLoader
{

    public function __construct()
    {
        parent::__construct();
        $this->init('demo');
    }

    public function onCommitted($isEnabled)
    {

        if(!$isEnabled)
            return;

        if(SessionManager::isLogged() && SessionManager::getData("manager")==1){
            return;
        }

        //2 = admin
        //3 = owner

        ConfigManager::setValue("default_demo_user",3);
        ConfigManager::setValue("default_demo_users",array(2,3,4));

        $script = $this->load->view('demo/pixels',NULL,TRUE);
        AdminTemplateManager::addScript($script);

        $scriptLibStaff = AdminTemplateManager::assets("demo","js/staff-web.js");
        AdminTemplateManager::addScriptLibs($scriptLibStaff);

        $scriptLibStaff = AdminTemplateManager::assets("demo","js/staff-admin.js");
        AdminTemplateManager::addScriptLibs($scriptLibStaff);

        //display demo list
        $this->setupDemoList();


    }


    private function setupDemoList(){

        $users = array();

        $users_id = ConfigManager::getValue("default_demo_users");
        $users_id = json_decode($users_id,JSON_OBJECT_AS_ARRAY);


        if(empty($users_id))
            return;

        foreach ($users_id as $id){
            $obj = $this->mUserModel->getUserData($id);
            if(!empty($obj))
                $users[] = $obj;
        }


        $html = "";

        foreach ($users as $user){
            $html .= $user['username']." / 123456<br>";
        }


        $script = $this->load->view('demo/global_script',array("html"=>$html),TRUE);
         AdminTemplateManager::addScript($script);

    }


    public function onLoad()
   {
       parent::onLoad(); // TODO: Change the autogenerated stub
   }


    public function onInstall()
    {
        return TRUE;
    }

    public function onUpgrade()
    {
        return TRUE;
    }

    public function onEnable()
    {
        return TRUE;
    }


    public function onAdminLoaded($module)
    {
        /*
         * return bool / function
         */

        return function (){



        };
    }
}